import numpy as np
import pandas as pd
import uuid
from ast import literal_eval
from dateutil import parser

# Set UUID namespace
namespace = uuid.UUID('12345678123456781234567812345678')

# Read original dataset
df = pd.read_csv('preprocessing/dataset.csv')

# Drop columns with too many NaN values that are not needed
df.drop(['price', 'likedPercent', 'firstPublishDate', 'edition',
        'rating', 'numRatings', 'bbeScore', 'bbeVotes'], axis=1, inplace=True)

# Replace empty strings with NaN
df.replace('', np.nan, inplace=True)

# Function to parse dates using dateutil
def parse_date(date_str):
    try:
        return pd.to_datetime(parser.parse(date_str), errors='coerce')
    except (ValueError, TypeError):
        return pd.NaT

# Convert to datetime, coercing errors (invalid dates will become NaT)
df['publishDate'] = df['publishDate'].apply(parse_date)
df['publishDate'] = df['publishDate'].apply(lambda x: x - pd.DateOffset(years=100) if x.year > 2024 else x)

# Correct invalid values in isbn and pages
df['isbn'] = df['isbn'].replace('9999999999999', np.nan)
df['pages'] = df['pages'].replace('0', np.nan)
df['genres'] = df['genres'].replace('[]', np.nan)

# Remove duplicate bookIds
df.drop_duplicates(subset='bookId', keep='first', inplace=True)

# Drop rows with NaN values in the specified columns
df.dropna(subset=['description', 'language', 'bookFormat', 'pages', 'publisher',
          'publishDate', 'coverImg', 'isbn', 'author', 'genres'], inplace=True)

# rename author into authors
df.rename(columns={'author': 'authors'}, inplace=True)

# Replace commas inside parentheses with a placeholder (e.g., ';')
df['authors'] = df['authors'].str.replace(r'\(.*?\)', '', regex=True)

# Replace "more…" with empty string
df['authors'] = df['authors'].str.replace(r', more…', '', regex=True)

# Create new DataFrames for authors, genres, publishers
authors = pd.DataFrame(df['authors'].str.split(
    ',').explode().str.strip().unique(), columns=['name'])
genres = pd.DataFrame(df['genres'].apply(
    literal_eval).explode().str.strip().unique(), columns=['name'])
publishers = pd.DataFrame(
    df['publisher'].str.strip().unique(), columns=['name'])

# # Assign mongodb uuid to each row
# authors['uuid'] = authors['name'].apply(lambda x: uuid.uuid5(namespace, str(x)).hex)
# genres['uuid'] = genres['name'].apply(lambda x: uuid.uuid5(namespace, str(x)).hex)
# publishers['uuid'] = publishers['name'].apply(lambda x: uuid.uuid5(namespace, str(x)).hex)

# Save the new DataFrames as JSON lists
authors.to_json('preprocessing/authors.json', orient='records')
genres.to_json('preprocessing/genres.json', orient='records')
publishers.to_json('preprocessing/publishers.json', orient='records')


# # Create dictionaries for quick lookups by 'name'
# author_dict = dict(zip(authors['name'], authors['uuid']))
# genre_dict = dict(zip(genres['name'], genres['uuid']))
# publisher_dict = dict(zip(publishers['name'], publishers['uuid']))

# Replace values in authors, genres, and publisher columns. Also trim
df['authors'] = df['authors'].str.split(',').apply(lambda x: [y.strip() for y in x])
df['genres'] = df['genres'].apply(literal_eval).apply(lambda x: [y.strip() for y in x])
df['publisher'] = df['publisher'].str.strip()

# Split the series field
df = df[~df['series'].str.contains(r'#.*-', na=False)]
df['numberInSeries'] = df['series'].apply(lambda x: ((int(x.split('#')[1].strip()) if x.split(
    '#')[1].strip().isnumeric() else None) if len(x.split('#')) > 1 else None) if isinstance(x, str) else None)
df['series'] = df['series'].apply(lambda x: x.split(
    '#')[0].strip() if isinstance(x, str) else None)

# Interpret JSON strings of other columns
df['characters'] = df['characters'].apply(literal_eval)
df['awards'] = df['awards'].apply(literal_eval)
df['ratingsByStars'] = df['ratingsByStars'].apply(literal_eval).apply(
    lambda x: {5-stars: int(reviews) for stars, reviews in enumerate(x)})
df['setting'] = df['setting'].apply(literal_eval)

# Calculate avgRating
df['rating'] = df['ratingsByStars'].apply(lambda x: sum(stars * reviews for stars, reviews in x.items()) / sum(x.values()) if sum(x.values()) > 0 else 0)

# Extract digits from pages and convert to int
df['pages'] = pd.to_numeric(
    df['pages'].str.extract('(\d+)')[0], errors='coerce')

# Set bookId as the index and add id column
df.set_index('bookId', inplace=True)
df['id'] = df.index

# Remove weird genres
df['genres'] = df['genres'].apply(lambda x: [genre for genre in x if isinstance(x, list) and genre not in ['Audiobook', 'Mira', "Hugo Awards", "Esp", "Apple", "Human Resources", "London Underground"]])

# Remove books with no genres
df = df[df['genres'].apply(lambda x: len(x) > 0)]

firstLayerTranslations = {
 "Young Adult": "Fiction" ,
 "Teen": "Fiction" ,
 "Middle Grade": "Fiction" ,
 "Childrens": "Fiction" ,
 "Fiction": "Fiction" ,
 "Dystopia": "Science Fiction" ,
 "Fantasy": "Fantasy" ,
 "Science Fiction": "Science Fiction" ,
 "Post Apocalyptic": "Science Fiction" ,
 "Science Fiction Fantasy": "Science Fiction" ,
 "Romance": "Romance" ,
 "Paranormal Romance": "Romance" ,
 "Historical Romance": "Romance" ,
 "Adventure": "Adventure" ,
 "Action": "Action" ,
 "Magic": "Fantasy" ,
 "Vampires": "Fantasy" ,
 "Paranormal": "Fantasy" ,
 "Supernatural": "Fantasy" ,
 "Urban Fantasy": "Fantasy" ,
 "Epic Fantasy": "Fantasy" ,
 "High Fantasy": "Fantasy" ,
 "Historical Fiction": "Historical" ,
 "Historical": "Historical" ,
 "War": "Historical" ,
 "Holocaust": "Historical" ,
 "World War II": "Historical" ,
 "Civil War": "Historical" ,
 "Books About Books": "Literature" ,
 "Literature": "Literature" ,
 "Politics": "Non-Fiction" ,
 "School": "Non-Fiction" ,
 "Read For School": "Non-Fiction" ,
 "Novels": "Fiction" ,
 "Classics": "Literature" ,
 "Picture Books": "Fiction" ,
 "Poetry": "Literature" ,
 "Juvenile": "Fiction" ,
 "Kids": "Fiction" ,
 "Short Stories": "Literature" ,
 "Gothic": "Literature" ,
 "19th Century": "Historical" ,
 "Classic Literature": "Literature" ,
 "Japan": "Location" ,
 "Adult": "Fiction" ,
 "Asia": "Location" ,
 "Adult Fiction": "Fiction" ,
 "British Literature": "Literature" ,
 "High School": "Fiction" ,
 "Plays": "Drama" ,
 "Drama": "Drama" ,
 "Philosophy": "Non-Fiction" ,
 "Spirituality": "Non-Fiction" ,
 "Self Help": "Non-Fiction" ,
 "Inspirational": "Non-Fiction" ,
 "Russia": "Location" ,
 "Russian Literature": "Literature" ,
 "Crime": "Mystery" ,
 "Angels": "Fantasy" ,
 "Canada": "Location" ,
 "Coming Of Age": "Fiction" ,
 "Animals": "Fiction" ,
 "Chapter Books": "Fiction" ,
 "American": "Location" ,
 "Time Travel": "Science Fiction" ,
 "Contemporary": "Fiction" ,
 "Chick Lit": "Fiction" ,
 "Magical Realism": "Fantasy" ,
 "Horror": "Horror" ,
 "Humor": "Comedy" ,
 "Comedy": "Comedy" ,
 "Fairy Tales": "Fantasy" ,
 "Mythology": "Fantasy" ,
 "Greek Mythology": "Fantasy" ,
 "Dragons": "Fantasy" ,
 "Epic": "Fantasy" ,
 "Mystery": "Mystery" ,
 "Monsters": "Horror" ,
 "Food": "Non-Fiction" ,
 "India": "Location" ,
 "Book Club": "Fiction" ,
 "Literary Fiction": "Literature" ,
 "20th Century": "Historical" ,
 "Unfinished": "Other" ,
 "Space Opera": "Science Fiction" ,
 "Thriller": "Thriller" ,
 "Apocalyptic": "Science Fiction" ,
 "Victorian": "Historical" ,
 "Scotland": "Location" ,
 "Realistic Fiction": "Fiction" ,
 "Family": "Fiction" ,
 "Suspense": "Thriller" ,
 "Mystery Thriller": "Thriller" ,
 "Feminism": "Non-Fiction" ,
 "LGBT": "LGBTQ" ,
 "African American": "Location" ,
 "New York": "Location" ,
 "Modern Classics": "Literature" ,
 "Religion": "Non-Fiction" ,
 "Nonfiction": "Non-Fiction" ,
 "Memoir": "Non-Fiction" ,
 "Biography": "Non-Fiction" ,
 "Ireland": "Location" ,
 "Autobiography": "Non-Fiction" ,
 "Biography Memoir": "Non-Fiction" ,
 "History": "Non-Fiction" ,
 "Irish Literature": "Literature" ,
 "Africa": "Location" ,
 "Steampunk": "Science Fiction" ,
 "Spanish Literature": "Literature" ,
 "Spain": "Location" ,
 "Economics": "Non-Fiction" ,
 "Contemporary Romance": "Romance" ,
 "Love": "Romance" ,
 "Womens": "Non-Fiction" ,
 "Queer": "LGBTQ" ,
 "Young Adult Fantasy": "Fantasy" ,
 "Travel": "Non-Fiction" ,
 "Psychology": "Non-Fiction" ,
 "Counting": "Education" ,
 "Storytime": "Education" ,
 "Mathematics": "Education" ,
 "Czech Literature": "Literature" ,
 "Italian Literature": "Literature" ,
 "Italy": "Location" ,
 "True Crime": "Non-Fiction" ,
 "Cats": "Fiction" ,
 "France": "Location" ,
 "Westerns": "Historical Fiction" ,
 "German Literature": "Literature" ,
 "Graphic Novels": "Comics" ,
 "Comics": "Comics" ,
 "Graphic Novels Comics": "Comics" ,
 "Comic Book": "Comics" ,
 "Superheroes": "Comics" ,
 "World War I": "Historical" ,
 "Theatre": "Drama" ,
 "Christmas": "Holiday" ,
 "Holiday": "Holiday" ,
 "Environment": "Non-Fiction" ,
 "China": "Location" ,
 "Arthurian": "Fantasy" ,
 "French Literature": "Literature" ,
 "Sweden": "Location" ,
 "Pirates": "Adventure" ,
 "Erotica": "Romance" ,
 "BDSM": "Romance" ,
 "Erotic Romance": "Romance" ,
 "Prehistoric": "Historical Fiction" ,
 "Medieval": "Historical Fiction" ,
 "Mental Health": "Non-Fiction" ,
 "Retellings": "Fantasy" ,
 "Witches": "Fantasy" ,
 "Japanese Literature": "Literature" ,
 "Detective": "Mystery" ,
 "Media Tie In": "Other" ,
 "Dinosaurs": "Science Fiction" ,
 "Biblical Fiction": "Religious Fiction" ,
 "Biblical": "Religious Fiction" ,
 "Indian Literature": "Literature" ,
 "Art": "Non-Fiction" ,
 "Christian": "Religious Fiction" ,
 "Banned Books": "Other" ,
 "Werewolves": "Fantasy" ,
 "Mental Illness": "Non-Fiction" ,
 "Dogs": "Fiction" ,
 "Portugal": "Location" ,
 "Portuguese Literature": "Literature" ,
 "Christian Fiction": "Religious Fiction" ,
 "Faith": "Religious Fiction" ,
 "Christianity": "Religious Fiction" ,
 "Journalism": "Non-Fiction" ,
 "Latin American": "Location" ,
 "Comic Strips": "Comics" ,
 "Race": "Non-Fiction" ,
 "Speculative Fiction": "Science Fiction" ,
 "Survival": "Adventure" ,
 "New Adult": "Fiction" ,
 "College": "Fiction" ,
 "Tragedy": "Drama" ,
 "Egypt": "Location" ,
 "Ancient History": "Historical" ,
 "Young Adult Contemporary": "Fiction" ,
 "Abuse": "Non-Fiction" ,
 "Nature": "Non-Fiction" ,
 "18th Century": "Historical" ,
 "Travelogue": "Non-Fiction" ,
 "Reference": "Non-Fiction" ,
 "Space": "Science Fiction" ,
 "Military Fiction": "Fiction" ,
 "Anthologies": "Literature" ,
 "Childrens Classics": "Literature" ,
 "Scandinavian Literature": "Literature" ,
 "Southern": "Location" ,
 "Cyberpunk": "Science Fiction" ,
 "Fae": "Fantasy" ,
 "English Literature": "Literature" ,
 "South Africa": "Location" ,
 "Science": "Non-Fiction" ,
 "Popular Science": "Non-Fiction" ,
 "Physics": "Non-Fiction" ,
 "Music": "Non-Fiction" ,
 "Death": "Non-Fiction" ,
 "Horses": "Fiction" ,
 "Ghosts": "Horror" ,
 "Regency": "Historical Fiction" ,
 "Germany": "Location" ,
 "Collections": "Literature" ,
 "Southern Gothic": "Literature" ,
 "Jewish": "Non-Fiction" ,
 "True Story": "Non-Fiction" ,
 "Taoism": "Non-Fiction" ,
 "Eastern Philosophy": "Non-Fiction" ,
 "Legal Thriller": "Thriller" ,
 "Law": "Non-Fiction" ,
 "Biology": "Non-Fiction" ,
 "Evolution": "Non-Fiction" ,
 "Anthropology": "Non-Fiction" ,
 "Political Science": "Non-Fiction" ,
 "Asian Literature": "Literature" ,
 "Young Adult Romance": "Romance" ,
 "Futuristic": "Science Fiction" ,
 "French Revolution": "Historical" ,
 "Judaism": "Religious Fiction" ,
 "Swedish Literature": "Literature" ,
 "American History": "Historical" ,
 "Christian Romance": "Romance" ,
 "Aliens": "Science Fiction" ,
 "Robots": "Science Fiction" ,
 "Essays": "Non-Fiction" ,
 "Ancient": "Historical" ,
 "Dark": "Fantasy" ,
 "Fairies": "Fantasy" ,
 "Folklore": "Fantasy" ,
 "Atheism": "Non-Fiction" ,
 "Theology": "Non-Fiction" ,
 "Zombies": "Horror" ,
 "Education": "Non-Fiction" ,
 "Pakistan": "Location" ,
 "The United States Of America": "Location" ,
 "Demons": "Horror" ,
 "Mountaineering": "Non-Fiction" ,
 "Sports": "Sports" ,
 "Medicine": "Non-Fiction" ,
 "Ethiopia": "Location" ,
 "Medical": "Non-Fiction" ,
 "Theory": "Non-Fiction" ,
 "Academic": "Non-Fiction" ,
 "Unicorns": "Fantasy" ,
 "Business": "Non-Fiction" ,
 "Leadership": "Non-Fiction" ,
 "Alternate History": "Historical Fiction" ,
 "Horse Racing": "Sports" ,
 "American Civil War": "Historical" ,
 "Espionage": "Thriller" ,
 "Social Justice": "Non-Fiction" ,
 "Astronomy": "Non-Fiction" ,
 "Presidents": "Historical" ,
 "American Revolution": "Historical" ,
 "Greece": "Location" ,
 "Nobel Prize": "Non-Fiction" ,
 "Noir": "Mystery" ,
 "Native Americans": "Location" ,
 "Writing": "Non-Fiction" ,
 "Botswana": "Location" ,
 "Love Story": "Romance" ,
 "Road Trip": "Adventure" ,
 "Sociology": "Non-Fiction" ,
 "Finance": "Non-Fiction" ,
 "Social Science": "Non-Fiction" ,
 "Health": "Non-Fiction" ,
 "Nutrition": "Non-Fiction" ,
 "Cooking": "Non-Fiction" ,
 "Disability": "Non-Fiction" ,
 "Halloween": "Holiday" ,
 "Aviation": "Non-Fiction" ,
 "Romanticism": "Literature" ,
 "Israel": "Location" ,
 "European History": "Historical" ,
 "Personal Development": "Non-Fiction" ,
 "Productivity": "Non-Fiction" ,
 "Management": "Non-Fiction" ,
 "Australia": "Location" ,
 "Fighters": "Sports" ,
 "Psychological Thriller": "Thriller" ,
 "Liberia": "Location" ,
 "Sierra Leone": "Location" ,
 "Art History": "Non-Fiction" ,
 "Beauty and The Beast": "Fantasy" ,
 "Fairy Tale Retellings": "Fantasy" ,
 "Outdoors": "Non-Fiction" ,
 "Roman": "Historical" ,
 "Murder Mystery": "Mystery" ,
 "Shapeshifters": "Fantasy" ,
 "Relationships": "Non-Fiction" ,
 "Marriage": "Non-Fiction" ,
 "Architecture": "Non-Fiction" ,
 "Hinduism": "Religious Fiction" ,
 "Animal Fiction": "Fiction" ,
 "Gay": "LGBTQ" ,
 "M M Romance": "Romance" ,
 "Novella": "Literature" ,
 "Brazil": "Location" ,
 "Denmark": "Location" ,
 "Danish": "Location" ,
 "Fashion": "Non-Fiction" ,
 "Computer Science": "Non-Fiction" ,
 "Lesbian": "LGBTQ" ,
 "Cults": "Non-Fiction" ,
 "Latin American Literature": "Literature" ,
 "Weird Fiction": "Fantasy" ,
 "Lovecraftian": "Horror" ,
 "Cultural": "Non-Fiction" ,
 "Dark Fantasy": "Fantasy" ,
 "Canadian Literature": "Literature" ,
 "Iran": "Location" ,
 "14th Century": "Historical" ,
 "Historical Mystery": "Mystery" ,
 "Batman": "Comics" ,
 "Dc Comics": "Comics" ,
 "Americana": "Non-Fiction" ,
 "Genetics": "Non-Fiction" ,
 "Emotion": "Non-Fiction" ,
 "New Age": "Non-Fiction" ,
 "Polish Literature": "Literature" ,
 "Womens Fiction": "Fiction" ,
 "New Weird": "Fantasy" ,
 "Sudan": "Location" ,
 "Diary": "Non-Fiction" ,
 "Buisness": "Non-Fiction" ,
 "Sports Romance": "Romance" ,
 "Christian Non Fiction": "Religious Fiction" ,
 "Tudor Period": "Historical" ,
 "Buddhism": "Religious Fiction" ,
 "Baseball": "Sports" ,
 "Young Adult Paranormal": "Fantasy" ,
 "Spy Thriller": "Thriller" ,
 "Elves": "Fantasy" ,
 "15th Century": "Historical" ,
 "Plantagenet": "Historical" ,
 "Skepticism": "Non-Fiction" ,
 "Police": "Mystery" ,
 "Catholic": "Religious Fiction" ,
 "Archaeology": "Non-Fiction" ,
 "Christian Living": "Non-Fiction" ,
 "Gardening": "Non-Fiction" ,
 "Historical Fantasy": "Fantasy" ,
 "Conspiracy Theories": "Non-Fiction" ,
 "Occult": "Fantasy" ,
 "Medieval History": "Historical" ,
 "World History": "Historical" ,
 "Nigeria": "Location" ,
 "African Literature": "Literature" ,
 "Military History": "Historical" ,
 "Ecology": "Non-Fiction" ,
 "Sustainability": "Non-Fiction" ,
 "Technology": "Non-Fiction" ,
 "Ukraine": "Location" ,
 "Utopia": "Science Fiction" ,
 "Personal Finance": "Non-Fiction" ,
 "Money": "Non-Fiction" ,
 "Entrepreneurship": "Non-Fiction" ,
 "Kenya": "Location" ,
 "Language": "Non-Fiction" ,
 "Linguistics": "Non-Fiction" ,
 "Rabbits": "Fiction" ,
 "Serbian Literature": "Literature" ,
 "Communication": "Non-Fiction" ,
 "Manga": "Comics" ,
 "Ghost Stories": "Horror" ,
 "Amazon": "Location" ,
 "Poverty": "Non-Fiction" ,
 "Social Issues": "Non-Fiction" ,
 "Parenting": "Non-Fiction" ,
 "Hard Boiled": "Mystery" ,
 "Wolves": "Fantasy" ,
 "Christian Fantasy": "Fantasy" ,
 "Aspergers": "Non-Fiction" ,
 "Social": "Non-Fiction" ,
 "Somalia": "Location" ,
 "Nordic Noir": "Mystery" ,
 "Gender": "Non-Fiction" ,
 "Gender Studies": "Non-Fiction" ,
 "Wildlife": "Non-Fiction" ,
 "Anime": "Comics" ,
 "Shojo": "Comics" ,
 "Comics Manga": "Comics" ,
 "Counter Culture": "Non-Fiction" ,
 "Indonesian Literature": "Literature" ,
 "Time Travel Romance": "Romance" ,
 "Lds": "Religious Fiction" ,
 "Church": "Religious Fiction" ,
 "Lds Non Fiction": "Religious Fiction" ,
 "Young Adult Historical Fiction": "Historical Fiction" ,
 "Cartoon": "Comics" ,
 "Artificial Intelligence": "Science Fiction" ,
 "16th Century": "Historical" ,
 "American Revolutionary War": "Historical" ,
 "Poland": "Location" ,
 "Islam": "Religious Fiction" ,
 "Forgotten Realms": "Fantasy" ,
 "Dungeons and Dragons": "Fantasy" ,
 "Dragonlance": "Fantasy" ,
 "Turkish Literature": "Literature" ,
 "Turkish": "Location" ,
 "Regency Romance": "Romance" ,
 "Modern": "Fiction" ,
 "Geography": "Non-Fiction" ,
 "Comic Fantasy": "Fantasy" ,
 "Romantic Suspense": "Romance" ,
 "Doctors": "Non-Fiction" ,
 "Chess": "Non-Fiction" ,
 "Martial Arts": "Non-Fiction" ,
 "Engineering": "Non-Fiction" ,
 "Pop Culture": "Non-Fiction" ,
 "Morocco": "Location" ,
 "Pulp": "Fiction" ,
 "Amish": "Fiction" ,
 "Wizards": "Fantasy" ,
 "Comix": "Comics" ,
 "Algeria": "Location" ,
 "Teaching": "Non-Fiction" ,
 "Boarding School": "Fiction" ,
 "Star Wars": "Science Fiction" ,
 "Cult Classics": "Literature" ,
 "Egyptian Literature": "Literature" ,
 "Bulgarian Literature": "Literature" ,
 "Clean Romance": "Romance" ,
 "Fitness": "Non-Fiction" ,
 "Metaphysics": "Philosophy" ,
 "Fantasy Romance": "Romance" ,
 "Adoption": "Non-Fiction" ,
 "17th Century": "Historical" ,
 "Natural History": "Non-Fiction" ,
 "Romantic": "Romance" ,
 "Mermaids": "Fantasy" ,
 "Christian Historical Fiction": "Historical Fiction" ,
 "Society": "Non-Fiction" ,
 "Mormonism": "Religious Fiction" ,
 "Neuroscience": "Non-Fiction" ,
 "Poetry Plays": "Literature" ,
 "Discipleship": "Religious Fiction" ,
 "21st Century": "Historical" ,
 "Menage": "Romance" ,
 "Musicians": "Non-Fiction" ,
 "13th Century": "Historical" ,
 "Mixed Martial Arts": "Non-Fiction" ,
 "Short Story Collection": "Literature" ,
 "M F Romance": "Romance" ,
 "Walking": "Non-Fiction" ,
 "Lebanon": "Location" ,
 "Young Adult Science Fiction": "Science Fiction" ,
 "Science Fiction Romance": "Science Fiction" ,
 "Gods": "Fantasy" ,
 "Rock N Roll": "Non-Fiction" ,
 "Mysticism": "Philosophy" ,
 "Romanian Literature": "Literature" ,
 "Psychoanalysis": "Non-Fiction" ,
 "Hard Science Fiction": "Science Fiction" ,
 "Ghana": "Location" ,
 "Health Care": "Non-Fiction" ,
 "Foodie": "Non-Fiction" ,
 "Activism": "Non-Fiction" ,
 "Urban": "Fiction" ,
 "Academia": "Non-Fiction" ,
 "Dying Earth": "Science Fiction" ,
 "Fostering": "Non-Fiction" ,
 "Rwanda": "Location" ,
 "Anarchism": "Non-Fiction" ,
 "Satanism": "Religious Fiction" ,
 "Transgender": "LGBTQ" ,
 "Design": "Non-Fiction" ,
 "12th Century": "Historical" ,
 "Chinese Literature": "Literature" ,
 "Sexuality": "Non-Fiction" ,
 "Lds Fiction": "Religious Fiction" ,
 "Belgium": "Location" ,
 "Film": "Non-Fiction" ,
 "Medieval Romance": "Romance" ,
 "Plants": "Non-Fiction" ,
 "Anti Racist": "Non-Fiction" ,
 "Western Romance": "Romance" ,
 "Hungarian Literature": "Literature" ,
 "Hungary": "Location" ,
 "Drawing": "Non-Fiction" ,
 "How To": "Non-Fiction" ,
 "Art Design": "Non-Fiction" ,
 "Anglo Saxon": "Historical" ,
 "Hockey": "Sports" ,
 "Video Games": "Games" ,
 "Gaming": "Non-Fiction" ,
 "Games": "Games" ,
 "Shonen": "Comics" ,
 "Maritime": "Non-Fiction" ,
 "Anthropomorphic": "Fantasy" ,
 "Military Science Fiction": "Science Fiction" ,
 "Logic": "Philosophy" ,
 "American Fiction": "Literature" ,
 "Favorites": "Non-Fiction" ,
 "Cities": "Non-Fiction" ,
 "Urban Planning": "Non-Fiction" ,
 "Finnish Literature": "Literature" ,
 "Heroic Fantasy": "Fantasy" ,
 "Sword and Sorcery": "Fantasy" ,
 "Vegan": "Non-Fiction" ,
 "Cozy Mystery": "Mystery" ,
 "Deception": "Non-Fiction" ,
 "Princesses": "Fantasy" ,
 "Bulgaria": "Location" ,
 "Textbooks": "Non-Fiction" ,
 "Technical": "Non-Fiction" ,
 "Virtual Reality": "Science Fiction" ,
 "Prayer": "Religious Fiction" ,
 "Photography": "Non-Fiction" ,
 "Criticism": "Non-Fiction" ,
 "Harlequin Teen": "Romance" ,
 "Banks": "Non-Fiction" ,
 "Belgian": "Location" ,
 "Sequential Art": "Comics" ,
 "Cycling": "Non-Fiction" ,
 "Russian History": "Historical" ,
 "Guides": "Non-Fiction" ,
 "Own": "Non-Fiction" ,
 "M F M": "Romance" ,
 "Superman": "Comics" ,
 "Fandom": "Non-Fiction" ,
 "Wicca": "Religious Fiction" ,
 "Bande Dessinée": "Comics" ,
 "Dutch Literature": "Literature" ,
 "Josei": "Comics" ,
 "Music Biography": "Non-Fiction" ,
 "Queer Lit": "LGBTQ" ,
 "The World": "Non-Fiction" ,
 "Programming": "Non-Fiction" ,
 "Native American History": "Historical" ,
 "Love Inspired": "Romance" ,
 "Love Inspired Historical": "Historical Fiction" ,
 "Literary Criticism": "Non-Fiction" ,
 "Journal": "Non-Fiction" ,
 "Georgian": "Historical" ,
 "Young Readers": "Fiction" ,
 "Brain": "Non-Fiction" ,
 "Lesbian Fiction": "LGBTQ" ,
 "Military Romance": "Romance" ,
 "Knitting": "Non-Fiction" ,
 "European Literature": "Literature" ,
 "Illness": "Non-Fiction" ,
 "Cinderella": "Fantasy" ,
 "Prostitution": "Non-Fiction" ,
 "Divorce": "Non-Fiction" ,
 "Geek": "Non-Fiction" ,
 "Computers": "Non-Fiction" ,
 "Birds": "Non-Fiction" ,
 "Epic Poetry": "Poetry" ,
 "Swashbuckling": "Adventure" ,
 "Transport": "Non-Fiction" ,
 "Government": "Non-Fiction" ,
 "New Adult Romance": "Romance" ,
 "God": "Religious Fiction" ,
 "Football": "Sports" ,
 "History Of Science": "Non-Fiction" ,
 "Counselling": "Non-Fiction" ,
 "Romania": "Location" ,
 "Cthulhu Mythos": "Horror" ,
 "Dictionaries": "Non-Fiction" ,
 "Journaling": "Non-Fiction" ,
 "Crafts": "Non-Fiction" ,
 "Prehistory": "Non-Fiction" ,
 "Spanish Civil War": "Historical" ,
 "Wilderness": "Non-Fiction" ,
 "Motorcycle": "Non-Fiction" ,
 "Number": "Non-Fiction" ,
 "International": "Non-Fiction" ,
 "Surreal": "Literature" ,
 "Us Presidents": "Non-Fiction" ,
 "Naval History": "Historical" ,
 "Cameroon": "Location" ,
 "Light Novel": "Comics" ,
 "Street Art": "Non-Fiction" ,
 "Graffiti": "Non-Fiction" ,
 "Terrorism": "Non-Fiction" ,
 "Seinen": "Comics" ,
 "Kazakhstan": "Location" ,
 "Classical Studies": "Non-Fiction" ,
 "Polygamy": "Non-Fiction" ,
 "Singularity": "Science Fiction" ,
 "Quantum Mechanics": "Science Fiction" ,
 "Futurism": "Non-Fiction" ,
 "Cookbooks": "Non-Fiction" ,
 "Fat Acceptance": "Non-Fiction" ,
 "Fat": "Non-Fiction" ,
 "Fat Studies": "Non-Fiction" ,
 "Womens Studies": "Non-Fiction" ,
 "Geometry": "Non-Fiction" ,
 "Scripture": "Religious Fiction" ,
 "Gothic Romance": "Romance" ,
 "Tasmania": "Location" ,
 "Humanities": "Non-Fiction" ,
 "Basketball": "Sports" ,
 "Recreation": "Non-Fiction" ,
 "Female Authors": "Non-Fiction" ,
 "Mine": "Non-Fiction" ,
 "Marvel": "Comics" ,
 "Social Work": "Non-Fiction" ,
 "Psychiatry": "Non-Fiction" ,
 "Fables": "Literature" ,
 "Sci Fi Fantasy": "Fantasy" ,
 "X Men": "Comics" ,
 "Harlequin": "Romance" ,
 "Hackers": "Non-Fiction" ,
 "Gay For You": "Romance" ,
 "Microhistory": "Non-Fiction" ,
 "Elizabethan Period": "Historical" ,
 "Bolivia": "Location" ,
 "Teachers": "Non-Fiction" ,
 "Fan Fiction": "Fiction" ,
 "African American Literature": "Literature" ,
 "Climbing": "Non-Fiction" ,
 "Soccer": "Sports" ,
 "Paranormal Mystery": "Mystery" ,
 "Class": "Non-Fiction" ,
 "Judaica": "Non-Fiction" ,
 "Culinary": "Non-Fiction" ,
 "Food and Drink": "Non-Fiction" ,
 "Zen": "Philosophy" ,
 "Human Development": "Non-Fiction" ,
 "Punk": "Music" ,
 "Oral History": "Non-Fiction" ,
 "Lesbian Romance": "Romance" ,
 "Holland": "Location" ,
 "Gay Fiction": "Fiction" ,
 "Splatterpunk": "Horror" ,
 "Interracial Romance": "Romance" ,
 "Reverse Harem": "Romance" ,
 "Albanian Literature": "Literature" ,
 "Internet": "Non-Fiction" ,
 "Urbanism": "Non-Fiction" ,
 "Urban Studies": "Non-Fiction" ,
 "Jazz": "Music" ,
 "Paganism": "Religious Fiction" ,
 "Church History": "Non-Fiction" ,
 "United States": "Location" ,
 "Near Future": "Science Fiction" ,
 "M M F": "Romance" ,
 "Graphic Novels Manga": "Comics" ,
 "Old Testament": "Religious Fiction" ,
 "Slice Of Life": "Fiction" ,
 "Chemistry": "Non-Fiction" ,
 "M M Fantasy": "Fantasy" ,
 "Nursery Rhymes": "Children's Literature" ,
 "Thelema": "Religious Fiction" ,
 "Magick": "Philosophy" ,
 "Esoterica": "Philosophy" ,
 "Research": "Non-Fiction" ,
 "Trains": "Non-Fiction" ,
 "Puzzles": "Non-Fiction" ,
 "Hip Hop": "Music" ,
 "History and Politics": "Non-Fiction" ,
 "Alternate Universe": "Science Fiction" ,
 "Diets": "Non-Fiction" ,
 "Climate Change": "Non-Fiction" ,
 "Bangladesh": "Location" ,
 "Palaeontology": "Non-Fiction" ,
 "Sword and Planet": "Science Fiction" ,
 "Science Nature": "Non-Fiction" ,
 "Social Media": "Non-Fiction" ,
 "Tea": "Non-Fiction" ,
 "Art and Photography": "Non-Fiction" ,
 "Visual Art": "Non-Fiction" ,
 "Western Historical Romance": "Historical Romance" ,
 "Burundi": "Location" ,
 "American Classics": "Literature" ,
 "Zimbabwe": "Location" ,
 "Semiotics": "Philosophy" ,
 "Firefighters": "Non-Fiction" ,
 "Plus Size": "Non-Fiction" ,
 "Folk Tales": "Literature" ,
 "Geology": "Non-Fiction" ,
 "Banking": "Non-Fiction" ,
 "Malawi": "Location" ,
 "Romanovs": "History" ,
 "2nd Grade": "Children's Literature" ,
 "Divination": "Philosophy" ,
 "Drinking": "Non-Fiction" ,
 "Food Writing": "Non-Fiction" ,
 "Polyamory": "Romance" ,
 "Pre K": "Children's Literature" ,
 "Climate Change Fiction": "Science Fiction" ,
 "Disease": "Non-Fiction" ,
 "Post Colonial": "Literature" ,
 "Harlequin Heartwarming": "Romance" ,
 "Asexual": "LGBTQ" ,
 "Wine": "Non-Fiction" ,
 "Baha I": "Religious Fiction" ,
 "Software": "Non-Fiction" ,
 "Coding": "Non-Fiction" ,
 "Usability": "Non-Fiction" ,
 "Website Design": "Non-Fiction" ,
 "African American Romance": "Romance" ,
 "Manhwa": "Comics" ,
 "40k": "Science Fiction" ,
 "Warcraft": "Fantasy" ,
 "World Of Warcraft": "Fantasy" ,
 "Togo": "Location" ,
 "Nerd": "Non-Fiction" ,
 "Soviet History": "History" ,
 "Russian Revolution": "History" ,
 "International Relations": "Non-Fiction" ,
 "Victor Frankenstein": "Fiction" ,
 "1st Grade": "Children's Literature" ,
 "Soldiers": "Non-Fiction" ,
 "Musicals": "Drama" ,
 "Labor": "Non-Fiction" ,
 "Doctor Who": "Science Fiction" ,
 "Feminist Theory": "Non-Fiction" ,
 "Mozambique": "Location" ,
 "School Stories": "Children's Literature" ,
 "Fire Services": "Non-Fiction" ,
 "Emergency Services": "Non-Fiction" ,
 "Buses": "Non-Fiction" ,
 "Tv": "Non-Fiction" ,
 "New Testament": "Religious Fiction" ,
 "Paranormal Urban Fantasy": "Fantasy" ,
 "Slash Fiction": "Fiction" ,
 "Yeti": "Fantasy" ,
 "Yaoi": "Romance" ,
 "Boys Love": "Romance" ,
 "Roman Britain": "Historical" ,
 "Category Romance": "Romance" ,
 "Buffy The Vampire Slayer": "Fantasy" ,
 "Genderqueer": "LGBTQ" ,
 "Amish Fiction": "Fiction" ,
 "Komik": "Comics" ,
 "Lenin": "History" ,
 "International Development": "Non-Fiction" ,
 "Star Trek": "Science Fiction" ,
 "Fractured Fairy Tales": "Fantasy" ,
 "Edwardian": "Historical" ,
 "Role Playing Games": "Games" ,
 "Growth Mindset": "Non-Fiction" ,
 "Mary Shelley": "Literature" ,
 "Intersex": "LGBTQ" ,
 "Weird West": "Fantasy" ,
 "Marathi": "Literature" ,
 "Planets": "Science Fiction" ,
 "Witchcraft": "Fantasy" ,
 "Libya": "Location" ,
 "Northern Africa": "Location" ,
 "Comedian": "Non-Fiction" ,
 "Shounen Ai": "Romance" ,
 "Alcohol": "Non-Fiction" ,
 "Bisexual": "LGBTQ" ,
 "Quilting": "Non-Fiction" ,
 "Pilots": "Non-Fiction" ,
 "Mali": "Location" ,
 "Rus": "History" ,
 "Spider Man": "Comics" ,
 "Vegetarian": "Non-Fiction" ,
 "Cryptozoology": "Non-Fiction" ,
 "Trivia": "Non-Fiction" ,
 "Victorian Romance": "Romance" ,
 "Harem": "Romance" ,
 "Ethnography": "Non-Fiction" ,
 "Planetary Romance": "Science Fiction" ,
 "Eritrea": "Location" ,
 "Google": "Non-Fiction" ,
 "Cultural Studies": "Non-Fiction" ,
 "International Literature": "Literature" ,
 "Frugal": "Non-Fiction" ,
 "Grad School": "Non-Fiction" ,
 "Pornography": "Non-Fiction" ,
 "Sex Work": "Non-Fiction" ,
 "Loveswept": "Romance" ,
 "Alternative Medicine": "Non-Fiction" ,
 "Reportage": "Non-Fiction" ,
 "Alchemy": "Fantasy" ,
 "Food History": "Non-Fiction" ,
 "Numerology": "Non-Fiction" ,
 "Supernatural Romance": "Romance" ,
 "Cocktails": "Non-Fiction" ,
 "Booze": "Non-Fiction" ,
 "Strippers": "Non-Fiction" ,
 "Museums": "Non-Fiction" ,
 "Museology": "Non-Fiction" ,
 "Agriculture": "Non-Fiction" ,
 "Horticulture": "Non-Fiction" ,
 "Battle Of Gettysburg": "History" ,
 "Evangelism": "Religious Fiction" ,
 "Lie": "Fiction" ,
 "Stories": "Fiction" ,
 "Sewing": "Non-Fiction" ,
 "Social Movements": "Non-Fiction" ,
 "NSFW": "Non-Fiction" ,
 "Mills and Boon": "Romance" ,
 "Webcomic": "Comics" ,
 "Ecclesiology": "Non-Fiction" ,
 "Muslims": "Non-Fiction" ,
 "Canon": "Religious Fiction" ,
 "Astrology": "Non-Fiction" ,
 "Students": "Non-Fiction" ,
 "Gay Erotica": "Romance" ,
 "Intelligent Design": "Non-Fiction" ,
 "M M M": "Romance" ,
 "Conservation": "Non-Fiction" ,
 "Erotic Horror": "Horror" ,
 "Tanzania": "Location" ,
 "M M Sports Romance": "Romance" ,
 "Star Trek The Next Generation": "Science Fiction" ,
 "Bizarro Fiction": "Fiction" ,
 "Academics": "Non-Fiction" ,
 "Omegaverse": "Romance" ,
 "Green": "Non-Fiction" ,
 "Zambia": "Location" ,
 "Love Inspired Suspense": "Romance" ,
 "Namibia": "Location" ,
 "Muslimah": "Religious Fiction" ,
 "Bicycles": "Non-Fiction" ,
 "Helicopters": "Non-Fiction" ,
 "Amateur Sleuth": "Mystery" ,
 "Cars": "Non-Fiction" ,
 "M M Historical Romance": "Romance" ,
 "Nazi Party": "History" ,
 "Futuristic Romance": "Romance" ,
 "Electrical Engineering": "Non-Fiction" ,
 "Read For College": "Education" ,
 "M M Contemporary": "Romance" ,
 "Goddess": "Fantasy" ,
 "Cartography": "Non-Fiction" ,
 "Harlequin Historical": "Romance" ,
 "Hqn": "Romance" ,
 "Angola": "Location" ,
 "Mail Order Brides": "Romance" ,
 "Geoffrey Chaucer": "Literature" ,
 "Golden Age Mystery": "Mystery" ,
 "Comics Bd": "Comics" ,
 "Yuri": "Romance" ,
 "Nursing": "Non-Fiction" ,
 "Harlequin Romance": "Romance" ,
 "Cryptids": "Non-Fiction" ,
 "Traditional Chinese Medicine": "Non-Fiction" ,
 "Georgian Romance": "Romance" ,
 "Viking Romance": "Romance" ,
 "Foster Parents": "Non-Fiction" ,
 "Field Guides": "Non-Fiction" ,
 "Ornithology": "Non-Fiction" ,
 "Multicultural Literature": "Literature" ,
 "Beer": "Non-Fiction" ,
 "Soviet Union": "History" ,
 "Figure Skating": "Non-Fiction" ,
 "Gender and Sexuality": "Non-Fiction" ,
 "Vaccines": "Non-Fiction" ,
 "Egyptology": "Non-Fiction" ,
 "Latin American History": "History" ,
 "11th Century": "Historical" ,
 "Norman": "Historical" ,
 "Harlequin Desire": "Romance" ,
 "Algorithms": "Non-Fiction" ,
 "Butch Femme": "LGBTQ" ,
 "Manga Romance": "Romance" ,
 "Uganda": "Location" ,
 "Creation Science": "Non-Fiction" ,
 "Naval Historical Fiction": "Historical Fiction" ,
 "Harlequin Blaze": "Romance" ,
 "Star Trek Deep Space Nine": "Science Fiction" ,
 "Silhouette": "Romance" ,
 "Adolescence": "Non-Fiction" ,
 "Gothic Horror": "Horror" ,
 "Choose Your Own Adventure": "Games" ,
 "Gamebooks": "Games" ,
 "Babylon 5": "Science Fiction" ,
 "Spiritualism": "Non-Fiction" ,
 "Fantasy Of Manners": "Fantasy" ,
 "\u6f2b\u753b": "Comics" ,
 "Ivory Coast": "Location" ,
 "Western Africa": "Location" ,
 "Republic Of The Congo": "Location" ,
 "Islamism": "Non-Fiction" ,
 "Woodwork": "Non-Fiction" ,
 "Web": "Non-Fiction" ,
 "Japanese History": "History" ,
 "World Of Darkness": "Fantasy" ,
 "Cross Dressing": "LGBTQ" ,
 "Fundamentalism": "Non-Fiction" ,
 "Harlequin Presents": "Romance" ,
 "M M Paranormal": "Romance" ,
 "Central Africa": "Location" ,
 "Railways": "Non-Fiction" ,
 "Anti Intellectualism": "Non-Fiction" ,
 "Game Design": "Non-Fiction" ,
 "Benin": "Location" ,
 "Taxation": "Non-Fiction" ,
 "Librarianship": "Non-Fiction" ,
 "Vegetarianism": "Non-Fiction" ,
 "Harlequin Nocturne": "Romance" ,
 "Pseudoscience": "Non-Fiction" ,
 "Queer Studies": "Non-Fiction" ,
 "Words": "Non-Fiction" ,
 "Cultural Heritage": "Non-Fiction" ,
 "Maps": "Non-Fiction" ,
 "Global Warming": "Non-Fiction" ,
 "Whodunit": "Mystery" ,
 "Gastronomy": "Non-Fiction" ,
 "Back To School": "Education" ,
 "M M Young Adult": "Romance" ,
 "Theosophy": "Non-Fiction" ,
 "Professors": "Non-Fiction" ,
 "Senegal": "Location" ,
 "Tarot": "Non-Fiction" ,
 "Jewellery": "Non-Fiction" ,
 "Disability Studies": "Non-Fiction" ,
 "Erotic Paranormal Romance": "Romance" ,
 "Herbs": "Non-Fiction" ,
 "Low Fantasy": "Fantasy" ,
 "Eastern Africa": "Location" ,
 "Christian Contemporary Fiction": "Romance" ,
 "Cuisine": "Non-Fiction" ,
 "Battle Of Britain": "History" ,
 "History Of Medicine": "History" ,
 "Moroccan": "Location" ,
 "Algebra": "Non-Fiction" ,
 "Did Not Finish": "Non-Fiction" ,
 "Brewing": "Non-Fiction" ,
 "Black Literature": "Literature" ,
 "Homeschool": "Education" ,
 "Social Change": "Non-Fiction" ,
 "Star Trek Original Series": "Science Fiction" ,
 "Colouring Books": "Non-Fiction" ,
 "Aeroplanes": "Non-Fiction" ,
 "Go": "Games" ,
 "Pre Raphaelite": "Art" ,
 "Graphic Novels Comics Manga": "Comics" ,
 "M M Science Fiction": "Science Fiction" ,
 "Mmorpg": "Games" ,
 "Goth": "Other" ,
 "Civil War History": "History" ,
 "Stuart": "Historical" ,
 "Wonder Woman": "Comics" ,
 "Library Science": "Non-Fiction" ,
 "Information Science": "Non-Fiction" ,
 "Star Trek Voyager": "Science Fiction" ,
 "Racing": "Non-Fiction" ,
 "Led Zeppelin": "Music" ,
 "Belief": "Non-Fiction" ,
 "Naturopathy": "Alternative Medicine" ,
 "Earth Sciences": "Non-Fiction" ,
 "Classical Music": "Music" ,
 "Food Preservation": "Non-Fiction" ,
 "M M Mystery": "Mystery" ,
 "Atlases": "Non-Fiction" ,
 "10th Century": "Historical" ,
 "Spanish History": "History" ,
 "Motorcycling": "Non-Fiction" ,
 "Civil War Eastern Theater": "History" ,
 "Traditional Regency": "Romance" ,
 "Ukrainian Literature": "Literature" ,
 "Royal Air Force": "Non-Fiction" ,
 "Jokes": "Humor" ,
 "Stand Up": "Comedy" ,
 "Warriors": "Fiction" ,
 "Peak Oil": "Non-Fiction" ,
 "Airships": "Non-Fiction" ,
 "Guinea": "Location" 
}

secondLayerTranslations = {
'Action': 'Action', 
'Adventure': 'Adventure', 
'Alternative Medicine': 'Other', 
'Art': 'Humanities', 
"Children's Literature": 'Literature',
'Comedy': 'Humor',
'Comics': 'Comics',
'Drama': 'Drama',
'Education': 'Education',
'Fantasy': 'Fantasy/Fiction',
'Fiction': 'Fantasy/Fiction',
'Games': 'Other',
'Historical': 'Historical',
'Historical Fiction': 'Historical',
'Historical Romance': 'Historical',
'History': 'Historical',
'Holiday': 'Other',
'Horror': 'Horror',
'Humor': 'Humor',
'LGBTQ': 'LGBTQ',
'Literature': 'Literature',
'Location': 'Geography',
'Music': 'Humanities',
'Mystery': 'Drama',
'Non-Fiction': 'Non-Fiction',
'Other': 'Other',
'Philosophy': 'Humanities',
'Poetry': 'Humanities', 
'Religious Fiction': 'Fantasy/Fiction',
'Romance': 'Drama',
'Science Fiction': 'Science Fiction',
'Sports': 'Other',
'Thriller': 'Drama'
}

def map_genres(specific_genres):
    broader_genres = {secondLayerTranslations[firstLayerTranslations[genre]] for genre in specific_genres}
    return list(broader_genres)

# TODO: This can be changed to broadGenres and we could modify the resolvers somehow to account for broudGenres and genres
df['genres'] = df['genres'].apply(map_genres)

# Save the DataFrame as a JSON list
df.to_json('preprocessing/books.json', orient='records')

